# Generated by Django 2.2.1 on 2019-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SshUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='终端登录用户名')),
                ('password', models.CharField(help_text='存放登录密码或者秘钥密码', max_length=200, verbose_name='密码')),
                ('ssh_key', models.TextField(blank=True, editable=False, null=True, verbose_name='秘钥信息')),
                ('is_key', models.BooleanField(default=True, help_text='默认以秘钥登录', verbose_name='是否使用秘钥登录')),
            ],
            options={
                'verbose_name': 'WebSSH登录信息',
                'verbose_name_plural': 'WebSSH登录信息',
            },
        ),
    ]
