# Generated by Django 2.2.1 on 2019-07-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webssh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='FortRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fort', models.CharField(max_length=32, verbose_name='登录主机及用户')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='远程地址')),
                ('start_time', models.CharField(max_length=64, verbose_name='开始时间')),
                ('login_status_time', models.CharField(max_length=16, verbose_name='登录时长')),
                ('record_file', models.CharField(max_length=256, verbose_name='操作记录')),
                ('record_mode', models.CharField(choices=[('ssh', 'ssh'), ('guacamole', 'guacamole')], default='ssh', max_length=10, verbose_name='登录协议')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作记录表',
                'verbose_name_plural': '操作记录表',
                'db_table': 'ops_fort_record',
            },
        ),
    ]
