# Generated by Django 2.2.1 on 2019-07-17 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0002_auto_20190717_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshuser',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
